spool get_roles_old.sql

        	SET PAGESIZE 10000;
		SET VERIFY OFF;
		SET term OFF;
		SET FEEDBACK OFF;

		exec dbms_metadata.set_transform_param(dbms_metadata.session_transform,'SQLTERMINATOR',TRUE);


		select dbms_metadata.get_ddl('ROLE' , role) 
		from dba_roles
		where role not in ('ADM_PARALLEL_EXECUTE_TASK'
		,'APEX_ADMINISTRATOR_ROLE'
		,'AQ_ADMINISTRATOR_ROLE'
		,'AQ_USER_ROLE'
		,'AUTHENTICATEDUSER'
		,'CAPI_USER_ROLE'
		,'CONNECT'
		,'CSW_USR_ROLE'
		,'CTXAPP'
		,'CWM_USER'
		,'DATAPUMP_EXP_FULL_DATABASE'
		,'DATAPUMP_IMP_FULL_DATABASE'
		,'DBA'
		,'DBFS_ROLE'
		,'DELETE_CATALOG_ROLE'
		,'EJBCLIENT'
		,'EXECUTE_CATALOG_ROLE'
		,'EXP_FULL_DATABASE'
		,'GATHER_SYSTEM_STATISTICS'
		,'GLOBAL_AQ_USER_ROLE'
		,'HS_ADMIN_EXECUTE_ROLE'
		,'HS_ADMIN_ROLE'
		,'HS_ADMIN_SELECT_ROLE'
		,'IMP_FULL_DATABASE'
		,'JAVADEBUGPRIV'
		,'JAVAIDPRIV'
		,'JAVASYSPRIV'
		,'JAVAUSERPRIV'
		,'JAVA_ADMIN'
		,'JAVA_DEPLOY'
		,'JMXSERVER'
		,'LBAC_DBA'
		,'LOGSTDBY_ADMINISTRATOR'
		,'MGMT_USER'
		,'OEM_ADVISOR'
		,'OEM_MONITOR'
		,'OLAPI_TRACE_USER'
		,'OLAP_DBA'
		,'OLAP_USER'
		,'OLAP_XS_ADMIN'
		,'ORDADMIN'
		,'OWB$CLIENT'
		,'OWB_DESIGNCENTER_VIEW'
		,'OWB_USER'
		,'PLUSTRACE'
		,'RECOVERY_CATALOG_OWNER'
		,'RESOURCE'
		,'SCHEDULER_ADMIN'
		,'SELECT_CATALOG_ROLE'
		,'SNMPAGENT'
		,'SPATIAL_CSW_ADMIN'
		,'SPATIAL_WFS_ADMIN'		
		,'WFS_USR_ROLE'
		,'WM_ADMIN_ROLE'
		,'XDBADMIN'
		,'XDB_SET_INVOKER'
		,'XDB_WEBSERVICES'
		,'XDB_WEBSERVICES_OVER_HTTP'
		,'XDB_WEBSERVICES_WITH_PUBLIC');

spool off
